include: .gitlab-variables.yaml

image: ghcr.io/akmalovaa/iac-tools

stages:
  - linter
  - terraform
  - ansible

.ansbile_prepare: &ansbile_prepare
    - echo "$ANSIBLE_VAULT" > ansible/vault.key
    - echo "$SSH_PRIVATE_KEY" > ansible/ssh/id_rsa
    - chmod -R 400 ./ansible/ssh

lint-docker-compose:
  stage: linter
  image: docker:dind
  script:
    - docker compose -f ./services/docker-compose.yaml config

create-vps:
  stage: terraform
  variables:
    TF_VAR_TWC_TOKEN: $TWC_TOKEN
  script:
    - task terraform:all # terraform init && terraform apply -refresh-only -auto-approve && terraform apply -auto-approve
  when: manual

deploy:
  stage: ansible
  variables:
    ANSIBLE_CONFIG: "./ansible/ansible.cfg"
  script:
    - *ansbile_prepare
    - task ansbile:play # ansible-playbook ansible/playbook.yaml
  when: manual
