version: '3'

env:
  IAC_TOOLS: 'docker run --rm -it -v .:/srv --env-file .env ghcr.io/akmalovaa/iac-tools'

includes:
  terraform: terraform/Taskfile.yaml
  ansible: ansible/Taskfile.yaml

tasks:
  bash:
    desc: "Only for exec iac tools container"
    cmds:
      - $IAC_TOOLS bash
  
  create_server:
    - task: terraform:all
    - task: ansible:play