---
# defaults settings

docker_main_dir: "{{ lookup('env', 'DOCKER_MAIN_DIR') | default('/srv/docker')}}"

# Gatus settings
gatus_image: "{{ lookup('env', 'GATUS_IMAGE') | default('twinproduction/gatus:latest') }}"

# Prometheus settings
prometheus_image: "{{ lookup('env', 'PROMETHEUS_IMAGE') | default('prom/prometheus:latest') }}"

# Grafana settings
grafana_image: "{{ lookup('env', 'GRAFANA_IMAGE') | default('grafana/grafana:latest') }}"
grafana_secret: "{{ lookup('env', 'GF_SECURITY_ADMIN_PASSWORD') | default('secret') }}"