---
# tasks file for install docker
- name: Install aptitude
  tags: install
  apt:
    name: aptitude
    state: latest
    update_cache: true

- name: Update cache & Full system update
  apt:
    update_cache: true
    upgrade: dist
    cache_valid_time: 432000

- name: Install a list of packages
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates 
      - curl 
      - gnupg

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present

- name: Debian-Based | Install Docker packages
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: yes